In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [226]:
dataset=pd.read_csv('C:/Users/vipul/Downloads/Reviews.csv')

In [227]:
dataset.head()


Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...  
2  "Delight" says it all  This is a confection that has been around a fe...  
3         Cough Medicine  If you are looking for the secret ingredient i...  
4            Great taffy  Great taffy at a great price.  There was a wid...

In [228]:
df=dataset
dataset['help']=dataset["HelpfulnessNumerator"]/dataset["HelpfulnessDenominator"]
dataset = dataset[np.isfinite(df['help'])]
dataset.shape

(298402, 11)

In [229]:
dataset=dataset.drop(['Id','ProductId','UserId','ProfileName','HelpfulnessNumerator','HelpfulnessDenominator','Time','Summary'],axis=1);

In [230]:
dataset.head()

Score                                               Text  help
0       5  I have bought several of the Vitality canned d...   1.0
2       4  This is a confection that has been around a fe...   1.0
3       2  If you are looking for the secret ingredient i...   1.0
8       5  Right now I'm mostly just sprouting this so my...   1.0
10      5  I don't know if it's the cactus or the tequila...   1.0

In [231]:

# if(dataset["help"]>0.5 and dataset['Score']>2):
#     dataset[label]=1

dataset['label'] = ((dataset['Score'] >2) & (df['help']>0.5))



In [232]:
contentAc=dataset['Text']
outcomeAc=dataset['label']

In [233]:
outcomeAc.head()

0      True
2      True
3     False
8      True
10     True
Name: label, dtype: bool

In [236]:
dataset1=dataset.drop(['Text'],axis=1)
dataset1=dataset.drop(['label'],axis=1)

In [237]:
want= 0.8*len(dataset)
X_testAc = dataset1[int(want):]
y_testAc = outcomeAc[int(want):]

X_testAc1 = contentAc[int(want):]
y_testAc1 = outcomeAc[int(want):]


In [238]:
dataset=dataset[:20000]
#X_testAc=X_testAc.drop(['Text'],axis=1)
print(X_testAc.shape,y_testAc.shape)

(59681, 3) (59681,)


In [270]:
X_testAc=X_testAc.drop(['Text'],axis=1)

In [239]:
# df=df.drop(['Id','ProductId','UserId','ProfileName','HelpfulnessNumerator','HelpfulnessDenominator','Time','Summary'],axis=1);


In [276]:
dataset.shape

(16692, 4)

In [241]:
dataset.head()

Score                                               Text  help  label
0       5  I have bought several of the Vitality canned d...   1.0   True
2       4  This is a confection that has been around a fe...   1.0   True
3       2  If you are looking for the secret ingredient i...   1.0  False
8       5  Right now I'm mostly just sprouting this so my...   1.0   True
10      5  I don't know if it's the cactus or the tequila...   1.0   True

In [242]:
dataset['label']
dataset.iloc[1,3]

True

In [243]:
dataset.shape

(20000, 4)

In [244]:
k=0;
for i in range(6000):
    if(k>4000):
        break;
    if(dataset.iloc[i,3]):
        k=k+1
        dataset.drop(dataset.index[[i]],inplace=True)
        
        

In [245]:
dataset.shape

(16692, 4)

In [246]:
dataset['label'].value_counts()

True     9587
False    7105
Name: label, dtype: int64

In [247]:
df=dataset
df.head()

Score                                               Text  help  label
2       4  This is a confection that has been around a fe...   1.0   True
3       2  If you are looking for the secret ingredient i...   1.0  False
10      5  I don't know if it's the cactus or the tequila...   1.0   True
12      1  My cats have been happily eating Felidae Plati...   1.0  False
14      5  The Strawberry Twizzlers are my guilty pleasur...   0.8   True

In [248]:
df=df.drop(['Text'],axis=1)


df=df.drop(['label'],axis=1)

In [249]:
df.head()

Score  help
2       4   1.0
3       2   1.0
10      5   1.0
12      1   1.0
14      5   0.8

In [250]:

content=dataset['Text']
outcome=dataset['label']

In [251]:
import nltk 

In [252]:

want= 0.8*len(df)

X_train = df[:int(want)]
y_train = outcome[:int(want)]
X_train1 = content[:int(want)]
y_train1 = outcome[:int(want)]

X_test1 = content[int(want):]
y_test1 = outcome[int(want):]
X_test = df[int(want):]
y_test = outcome[int(want):]

print(len(X_test1))
print(len(y_test1))

print(X_train.shape)
print(len(y_train))

3339
3339
(13353, 2)
13353


In [253]:
from sklearn.naive_bayes import MultinomialNB

In [254]:
from sklearn.metrics import accuracy_score

In [255]:
from sklearn.pipeline import Pipeline

In [256]:
print(X_train)

       Score      help
2          4  1.000000
3          2  1.000000
10         5  1.000000
12         1  1.000000
14         5  0.800000
26         1  0.000000
27         4  0.000000
31         5  0.000000
33         4  1.000000
35         4  1.000000
37         5  1.000000
47         3  0.500000
48         4  0.500000
49         3  0.000000
50         1  0.000000
52         4  1.000000
56         5  1.000000
60         3  0.500000
61         5  0.000000
62         1  1.000000
64         5  1.000000
67         2  0.000000
69         5  0.000000
71         5  1.000000
73         1  0.000000
81         4  1.000000
83         3  1.000000
85         5  1.000000
87         5  1.000000
99         1  0.000000
...      ...       ...
33005      5  0.750000
33006      5  1.000000
33014      5  0.000000
33015      5  1.000000
33016      5  0.833333
33017      5  0.800000
33018      1  0.714286
33019      4  0.666667
33021      5  0.333333
33022      5  1.000000
33023      5  1.000000
33024      

In [257]:
# train=X_train['Text']
# test=X_test['Text']

In [258]:

from sklearn.feature_extraction.text import TfidfTransformer

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(min_df=1,stop_words='english')

from sklearn.model_selection import GridSearchCV

In [259]:

X_trainf=tf.fit_transform(X_train1)
X_testf=tf.transform(X_test1)

X_testfAc=tf.transform(X_testAc1)

In [ ]:
print(X_trainf);

In [ ]:
type(X_testf)

In [196]:
train=X_trainf.toarray()



MemoryError: 

In [ ]:

test=X_testf.toarray()

In [260]:
testAc=X_testfAc.toarray()

MemoryError: 

In [261]:
mnb3=MultinomialNB()

In [262]:
len(y_train)

13353

In [263]:
train.shape

(13353, 23573)

In [264]:
mnb3.fit(train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [265]:
p=mnb3.predict(X_testfAc)

In [266]:
e=accuracy_score(y_testAc,p)
print(e)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_testAc, p)

0.749602050904


array([[ 7738, 12405],
       [ 2539, 36999]], dtype=int64)

In [267]:
mnb2=MultinomialNB()

In [268]:
mnb2.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [271]:
p1=mnb2.predict(X_testAc)

In [272]:
X_train.shape

(13353, 2)

In [273]:
e=accuracy_score(y_testAc,p1)
print(e)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_testAc, p1)

0.662488899315


array([[    0, 20143],
       [    0, 39538]], dtype=int64)

In [274]:
# a=p==p1

count=0
pred=p1

for i in range(len(p1)):
    if(p[i]==True and p1[i]==True):
        pred[i]=True
    else:
        pred[i]=False
    #pred[i]=False   
    

In [275]:
e=accuracy_score(y_testAc,pred)
print(e)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_testAc, pred)

0.749602050904


array([[ 7738, 12405],
       [ 2539, 36999]], dtype=int64)

In [288]:
from sklearn.linear_model import SGDClassifier
text_clf = Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf-svm', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, random_state=42,n_iter=5)), ])


In [289]:
text_clf.fit(X_train1, y_train1)
predicted = text_clf.predict(X_testAc1)
e=accuracy_score(y_testAc1,predicted)
print(e)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


0.758633400915


In [290]:
from sklearn.model_selection import GridSearchCV
parameters = {'vect__ngram_range': [(1, 1), (1, 2)],
               'tfidf__use_idf': (True, False),
               'clf-svm__alpha': (1e-2, 1e-3),
 }

In [291]:
gs_clf = GridSearchCV(text_clf, parameters, n_jobs=-1)
gs_clf = gs_clf.fit(X_train1, y_train1)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


In [292]:
predicted = gs_clf.predict(X_testAc1)
e=accuracy_score(y_testAc1,predicted)
print(e)

0.758633400915


In [293]:
import nltk
nltk.download()
from nltk.stem.snowball import SnowballStemmer




showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


In [294]:
stemmer = SnowballStemmer("english", ignore_stopwords=True)
class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(StemmedCountVectorizer, self).build_analyzer()
        return lambda doc: ([stemmer.stem(w) for w in analyzer(doc)])

In [295]:
stemmed_count_vect = StemmedCountVectorizer(stop_words='english')
text_mnb_stemmed = Pipeline([('vect', stemmed_count_vect),
                      ('tfidf', TfidfTransformer()),
                      ('clf-svm', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, random_state=42,n_iter=5)),
 ])

In [296]:
text_mnb_stemmed = text_mnb_stemmed.fit(X_train1, y_train1)
predicted_mnb_stemmed = text_mnb_stemmed.predict(X_testAc1)
e=accuracy_score(y_testAc1,predicted)
print(e)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:117: DeprecationWarning: n_iter parameter is deprecated in 0.19 and will be removed in 0.21. Use max_iter and tol instead.
  DeprecationWarning)


0.758633400915


In [ ]:
//finish

In [141]:
from sklearn.neural_network import MLPClassifier


clf = MLPClassifier(solver='lbfgs',hidden_layer_sizes=(2,2) alpha=1e-5,
                      random_state=1)
                        


SyntaxError: invalid syntax (<ipython-input-141-6c093d647c43>, line 4)

In [362]:
from sklearn import svm

clf = svm.SVC(gamma='scale')


In [371]:

# clf.fit(train_data, y_train)  
print(type(y_train))

<class 'list'>


In [372]:
clf.fit(train_data,y_train) 

TypeError: must be real number, not str

In [ ]:
clf.predict(test_data)

In [166]:
mnb1=MultinomialNB()
mnb2=MultinomialNB()


In [167]:
# # y_train1=np.zeros((int(want)), dtype=object)
# # y_train1 = label[:int(want)]
# # print(type(y_train1))

# t=train_data.tolist()
# if(len(t)==len(y_train)):
#     print("hi")
# print(t[0])
# print(y_train[0])



hi
[<1x86028 sparse matrix of type '<class 'numpy.float64'>'
	with 19 stored elements in Compressed Sparse Row format>, 5.0, 1.0]
0


In [168]:
t[0][0]

<1x86028 sparse matrix of type '<class 'numpy.float64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [169]:
mnb1.fit(X_trainf,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [170]:
print(len(X_train1))

238721


In [171]:
mnb2.fit(X_train1, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [172]:
X_trainf

<238721x86028 sparse matrix of type '<class 'numpy.float64'>'
	with 8148774 stored elements in Compressed Sparse Row format>

In [173]:
X_test1=X_test.drop('Text',axis=1)

In [174]:
pred1=mnb1.predict(X_testf)
pred2=mnb2.predict(X_test1)

In [333]:
from sklearn.metrics import accuracy_score
# e=accuracy_score(y_test,pred1)
# print(e)

In [176]:
e=accuracy_score(y_test,pred2)
print(e)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred1)

0.712303748262


In [177]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred1)

array([[41915,   596],
       [12517,  4653]], dtype=int64)

In [178]:
confusion_matrix(y_test, pred2)

array([[42511,     0],
       [17170,     0]], dtype=int64)

In [180]:
len(t)

238721

In [181]:
# mnb3.fit(t,y_train)

In [107]:
from sklearn.linear_model import SGDClassifier
text_clf = Pipeline([('vect', CountVectorizer()),('tfidf', TfidfTransformer()),('clf', SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, random_state=42,max_iter=5, tol=None)), ])


In [109]:
text_clf.fit(X_train, y_train)
predicted = text_clf.predict(X_test)
e=accuracy_score(y_test,predicted)
print(e)

In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predicted)

array([[84912,    11],
       [34140,   298]], dtype=int64)

In [113]:
X_trainf=tf.fit_transform(X_train)

X_trainf

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [114]:
X_testf=tf.transform(X_test)

mnb1=MultinomialNB()


In [115]:
from sklearn import svm

In [160]:
# # x_traintf

# mnb1.fit(X_trainf,y_train)

# clf = svm.SVC(gamma='scale')
# clf.fit(X_trainf,y_train)  


In [155]:
#p=mnb1.predict(X_testf)

pred1=mnb1.predict(X_testf)
X_test1=X_test.drop('Text',axis=1)
pred2=mnb2.predict(X_test1)
# p=clf.predict(X_testf)

In [ ]:
pred2=mnb2.predict(X_test)

In [ ]:
len(p)

In [ ]:
X_testf.shape

In [ ]:
len(y_test)

In [ ]:
e=accuracy_score(y_test,p)

In [ ]:
e

In [213]:
dataset.head()

Id   ProductId          UserId                      ProfileName  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW                       delmartian   
1   2  B00813GRG4  A1D87F6ZCVE5NK                           dll pa   
2   3  B000LQOCH0   ABXLMWJIXXAIN  Natalia Corres "Natalia Corres"   
3   4  B000UA0QIQ  A395BORC6FGVXV                             Karl   
4   5  B006K2ZZ7K  A1UQRSCLF8GW1T    Michael D. Bigham "M. Wassir"   

   HelpfulnessNumerator  HelpfulnessDenominator  Score        Time  \
0                     1                       1      5  1303862400   
1                     0                       0      1  1346976000   
2                     1                       1      4  1219017600   
3                     3                       3      2  1307923200   
4                     0                       0      5  1350777600   

                 Summary                                               Text  
0  Good Quality Dog Food  I have bought several of the Vitality canned d...  
1      Not as Advertised  Product arrived labeled as Jumbo Salted Peanut...  
2  "Delight" says it all  This is a confection that has been around a fe...  
3         Cough Medicine  If you are looking for the secret ingredient i...  
4            Great taffy  Great taffy at a great price.  There was a wid...

In [214]:
import numpy as np

In [220]:
label=[]
content=[]
k=0
for i in range(len(dataset)):
    if(dataset['HelpfulnessDenominator'][i]==0):
        continue
   
    elif((dataset['HelpfulnessNumerator'][i]/dataset['HelpfulnessDenominator'][i])>=0.5 and dataset['Score'][i]>2 and np.std(len(dataset['Text']))<0.9 ):
        label.append(0)
        content.append(dataset['Text'][i])
        
    else:
        label.append(1)
        content.append(dataset['Text'][i])

In [45]:
c=dataset["ProductId"]
type(c)

pandas.core.series.Series

In [176]:
count = 0
for i in y_test:
    if i==1:
        count+=1
        
print(count)
print(len(label)-count)

34438
263964


array([[84912,    11],
       [34140,   298]], dtype=int64)

In [46]:
/d=c.unique()

In [47]:
d

array(['B001E4KFG0', 'B00813GRG4', 'B000LQOCH0', ..., 'B003S1WTCU',
       'B004I613EE', 'B001LR2CU2'], dtype=object)

In [48]:
c=dataset["UserId"].unique()
c

array(['A3SGXH7AUHU8GW', 'A1D87F6ZCVE5NK', 'ABXLMWJIXXAIN', ...,
       'A28KG5XORO54AY', 'A121AA1GQV751Z', 'A3LGQPJCZVL9UC'], dtype=object)

In [49]:
len(c)

256059

In [50]:
a=["The candy is just red , No flavor . Just  plan and chewy .  I would never buy them again"]
b=tf.transform(a)

In [51]:
p=mnb1.predict(b)

In [52]:
p[0]

0

In [53]:
count=0;
for i in range(len(y_test)):
    if(y_test[i]==0):
        count+=1
        

In [54]:
count

84923

In [55]:
len(y_test)

119361

In [67]:
len(p)

1

In [56]:
count/len(y_test)

0.7114802992602274